<font color='blue'><h1>Introdução Prática ao PyTorch</h1></font>
<font color='blue'><h2>Tensores</h2></font>

**Framework Pytorch**
- Uma biblioteca de tensores otimizada para Deep Learning via GPUs e CPUs

**Instruções de Instalação**:
- https://pytorch.org/get-started/locally/

<font color='0471A6'><h2>⭐ Tensores em PyTorch</h2></font>


- Estruturas de dados semelhantes aos arrays e matrizes
- Similares aos arrays do Numpy, mas também ser executados em GPU
- Otimizados para diferenciação automática (Recurso *AutoGrad*)

In [2]:
'''
Exemplos de Tensores em PyTorch
(Vários dos Exemplos estão disponíveis na documentação oficial)
https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html
'''

import torch
import numpy as np

In [47]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

x_data, x_data.dtype

(tensor([[1, 2],
         [3, 4]]),
 torch.int64)

In [49]:
# data type
print(x.dtype)

torch.float32


In [44]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

x_np, x_np.dtype

(tensor([[1, 2],
         [3, 4]]),
 torch.int64)

In [52]:
# tensor vazio
x = torch.empty(1) 
x = torch.empty(3) 
x = torch.empty(2,2)

x, x.dtype

(tensor([[3.8235e-40, 0.0000e+00],
         [0.0000e+00, 1.1755e-38]]),
 torch.float32)

In [53]:
# Tensor a partir de um array Numpy
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [54]:
# Tensor a partir de um array Numpy
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.5044, 0.1437],
        [0.7540, 0.5121]])

In [55]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [56]:
# especifica o tipo
x = torch.zeros(5,3, dtype=torch.float)
x = torch.ones(5,3, dtype=torch.float)

In [15]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [17]:
if torch.cuda.is_available():
    print("GPU disponível!")
else:
    print("Não há GPUs disponíveis. Vamos usar a  CPU.")

GPU disponível!


In [18]:
torch.cuda.device_count()

1

In [19]:
# Move o tensor para a GPU (Se disponível)
tensor = torch.rand(3,4)
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

In [20]:
# Move o tensor para a GPU (Se disponível)
tensor = torch.rand(3,4)
if torch.cuda.is_available():
  tensor = tensor.to('cuda:0')

In [21]:
tensor = torch.rand(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([0.9709, 0.8428, 0.1271, 0.6474])
First column:  tensor([0.9709, 0.7422, 0.6711, 0.6251])
Last column: tensor([0.6474, 0.2816, 0.3847, 0.1289])
tensor([[0.9709, 0.0000, 0.1271, 0.6474],
        [0.7422, 0.0000, 0.0177, 0.2816],
        [0.6711, 0.0000, 0.3947, 0.3847],
        [0.6251, 0.0000, 0.0696, 0.1289]])


In [22]:
# concatenação de tensores
print(tensor.shape)

t1 = torch.cat([tensor, tensor, tensor], dim=1) # col dim
print(t1.shape)

torch.Size([4, 4])
torch.Size([4, 12])


In [23]:
# concatenação de tensores
t1 = torch.cat([tensor, tensor, tensor], dim=0) # row dim
print(t1.shape)

torch.Size([12, 4])


In [25]:
# Multiplicação de Matrizes entre os tensores (y1, y2 e y3 terão o mesmo valor)

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

tensor, y1, y2, y3

(tensor([[0.9709, 0.0000, 0.1271, 0.6474],
         [0.7422, 0.0000, 0.0177, 0.2816],
         [0.6711, 0.0000, 0.3947, 0.3847],
         [0.6251, 0.0000, 0.0696, 0.1289]]),
 tensor([[1.3780, 0.9052, 0.9508, 0.6992],
         [0.9052, 0.6305, 0.6134, 0.5014],
         [0.9508, 0.6134, 0.7541, 0.4965],
         [0.6992, 0.5014, 0.4965, 0.4122]]),
 tensor([[1.3780, 0.9052, 0.9508, 0.6992],
         [0.9052, 0.6305, 0.6134, 0.5014],
         [0.9508, 0.6134, 0.7541, 0.4965],
         [0.6992, 0.5014, 0.4965, 0.4122]]),
 tensor([[1.3780, 0.9052, 0.9508, 0.6992],
         [0.9052, 0.6305, 0.6134, 0.5014],
         [0.9508, 0.6134, 0.7541, 0.4965],
         [0.6992, 0.5014, 0.4965, 0.4122]]))

In [26]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

5.060935974121094 <class 'float'>


In [27]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [32]:
t = torch.ones(5,5)
a_numpy_array = t.numpy()

a_numpy_array, a_numpy_array.dtype

(array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=float32),
 dtype('float32'))

In [34]:
# Criar um tensor em um dispositivo selecionadotensor
tensor = torch.randn(2, 3).to("cpu")
tensor, tensor.device

(tensor([[-1.0399,  1.3423, -1.2026],
         [ 0.2354, -0.2294, -0.2538]]),
 device(type='cpu'))

In [39]:
# Criar um tensor em um dispositivo selecionadotensor
tensor = torch.randn(2, 3).to("cuda:0")
tensor, tensor.device

(tensor([[-0.1456, -0.3950,  0.5641],
         [-0.0854, -0.4671, -0.8912]], device='cuda:0'),
 device(type='cuda', index=0))

In [67]:
t = torch.randn(2, 3).to("cuda:0")
t = t.cpu() # move o tensor da memória da Gpu para a memória da Cpu
a_numpy_array = t.numpy()

In [69]:
# suporte à gpu
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
x = torch.rand(2,3).to(device)
x = torch.rand(2,3, device = device)

In [3]:
# Mover o tensor para a GPU
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

NameError: name 'tensor' is not defined

In [4]:
# Redimensiona com torch.view()
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [7]:
x1 = torch.randn(4,4).to("cuda:0")
x2 = torch.randn(4,4).to("cuda:0")
x1+x2

tensor([[-0.4422, -0.9332, -0.9442,  1.0218],
        [-2.2616,  2.6691, -0.7213,  2.0097],
        [-1.9261,  0.5379,  3.0758, -1.5125],
        [-0.2600, -1.6334,  0.2398, -2.2586]], device='cuda:0')

In [57]:
tensor = torch.rand(150,4)
print(tensor.shape)

# redimensiona o tensor como um vetor unidimensional
print(tensor.view(-1).shape)

torch.Size([150, 4])
torch.Size([600])


In [61]:
# redimensiona o tensor como um vetor unidimensional
# adicionando uma dimensão no início
tensor = torch.rand(3,4)
print(tensor.view(1, -1).shape)

torch.Size([1, 12])


In [63]:
images = torch.randn(64, 1, 512, 512)
print(images.shape)

# Remove a dimensao 1
images_squeezed = images.squeeze(dim=1)
print(images_squeezed.shape)

torch.Size([64, 1, 512, 512])
torch.Size([64, 512, 512])


In [64]:
# Adiciona dimensao de tamanho 1
images_unsqueezed = images_squeezed.unsqueeze(dim=1)
print(images_unsqueezed.shape)

torch.Size([64, 1, 512, 512])


In [65]:
x = torch.randn(1)
print(x)

# o valor do tensor com um único elemento
print(x.item())

tensor([-0.5158])
-0.5158449411392212


In [10]:
a = np.ones(5)
b = torch.from_numpy(a)
c = torch.tensor(a)
d = a.copy()

print(a)
print(b)
print(c)

# cuidado ao modificar. compartilhamento de memõria entre tensores numpy e torch
a += 1
print("a",a)
print("b",b)
print("c", c)
print("d", d)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
a [2. 2. 2. 2. 2.]
b tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
c tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
d [1. 1. 1. 1. 1.]


In [70]:
# AutoGrad - Fornece diferenciação automática para as operações com tensores 
# Pytorch possui uma engine de diferenciação chamada Autograd para o cômputo dos gradientes de qualquer grafo computacional

# requires_grad=True dirá ao PyTorch para calcular os gradientes para o tensor
import torch
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2
print(y)

tensor(9., grad_fn=<PowBackward0>)


In [71]:
print(x.grad)

None


In [72]:
# calcula-se o gradiente com backpropagation
y.backward()

In [73]:
# obtém o gradiente
# derivada dy/dx --> derivada de X**2 --> 2x
# para x = 3 --> 2*x = 2*3 = 6.
print(x.grad)

tensor(6.)


In [74]:
# Para impedir o cômputo de gradientes - Uma forma
x = torch.tensor(3.0, requires_grad=True)
print(x)
x.requires_grad_(False)
print(x)

tensor(3., requires_grad=True)
tensor(3.)


In [75]:
# Para impedir o cômputo de gradientes - Outra forma
x = torch.tensor(3.0, requires_grad=True)
print(x)
x = x.detach()
print(x, x.requires_grad)

tensor(3., requires_grad=True)
tensor(3.) False


In [76]:
# Para impedir o cômputo de gradientes - Mais outra forma
# Aqui, desabilita-se (temporariamente) o cômputo de gradientes
# no bloco de código identado
x = torch.tensor(3.0, requires_grad=True)
with torch.no_grad():
  print(x)

tensor(3., requires_grad=True)
