<font color='blue'><h1>Introdução Prática ao PyTorch</h1></font>
<font color='0471A6'><h2>Rede Neural em PyTorch (Visão Geral)</h2></font>

In [2]:
'''
Exemplo Simples de Rede Neural em PyTorch
(Utilizando o nn.Sequential)
'''

# Define a Rede Neural
import torch
import torch.nn as nn

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.seq = nn.Sequential(
            nn.Linear(4, 8),
            nn.Sigmoid(),
            nn.Linear(8, 1),
            nn.Sigmoid()
        )
        
    def forward(self, x):
        return self.seq(x)

# Cria uma instância da classe
net = Net()

# Exemplo de Feed-Forward
input_data = torch.tensor([[1.0, 2.0, 3.0, 4.0]])
output = net(input_data)
print(output)
print(output.item())

tensor([[0.4873]], grad_fn=<SigmoidBackward0>)
0.4873144328594208


In [3]:
'''
Exemplo Simples de Rede Neural em PyTorch
(Sem utilizar o nn.Sequential - Mais Flexibilidade!)
'''

import torch
import torch.nn as nn

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(4, 8)
        self.fc2 = nn.Linear(8, 1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, x):
        x = self.fc1(x)
        x = self.sigmoid(x)
        x = self.fc2(x)
        x = self.sigmoid(x)
        return x

# Cria uma instância da classe
net = Net()

# Exemplo de Feed-Forward
input_data = torch.tensor([[1.0, 2.0, 3.0, 4.0]])
output = net(input_data)
print(output)
print(output.item())

tensor([[0.2987]], grad_fn=<SigmoidBackward0>)
0.2986525893211365


In [4]:
# Obtém o "device" para treinamento
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Dispositivo: {device}")

# move-se para o dispositivo
model = Net().to(device)

Dispositivo: cuda


In [5]:
'''
Parâmetros Livres do Modelo (Pesos da Rede)
'''
print(f"Estrutura da Rede: {model}\n\n")

for name, param in model.named_parameters():
    print(f"Camada: {name} | Size: {param.size()}")
    print(f'| Valores : {param[:2]}... \n')

Estrutura da Rede: Net(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (fc2): Linear(in_features=8, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)


Camada: fc1.weight | Size: torch.Size([8, 4])
| Valores : tensor([[-0.1007, -0.3197,  0.1680, -0.3032],
        [-0.4257,  0.0383, -0.2670,  0.1249]], device='cuda:0',
       grad_fn=<SliceBackward0>)... 

Camada: fc1.bias | Size: torch.Size([8])
| Valores : tensor([-0.4315,  0.2424], device='cuda:0', grad_fn=<SliceBackward0>)... 

Camada: fc2.weight | Size: torch.Size([1, 8])
| Valores : tensor([[-0.3372, -0.2840, -0.3524, -0.1453,  0.2820, -0.1466,  0.2536, -0.3121]],
       device='cuda:0', grad_fn=<SliceBackward0>)... 

Camada: fc2.bias | Size: torch.Size([1])
| Valores : tensor([0.2877], device='cuda:0', grad_fn=<SliceBackward0>)... 



<font color='0471A6'><h2>Persistência e Carregamento de Modelo</h2></font>

In [6]:
# Parâmetros do modelo de rede neural
model.state_dict()

OrderedDict([('fc1.weight',
              tensor([[-0.1007, -0.3197,  0.1680, -0.3032],
                      [-0.4257,  0.0383, -0.2670,  0.1249],
                      [-0.1990,  0.0999, -0.1773,  0.3004],
                      [-0.1840,  0.1197,  0.4813, -0.2146],
                      [-0.0772, -0.2214, -0.4853,  0.4462],
                      [ 0.1429, -0.1724,  0.2718, -0.2958],
                      [ 0.0070,  0.1838, -0.3497, -0.2996],
                      [ 0.0972, -0.0601, -0.2278, -0.2652]], device='cuda:0')),
             ('fc1.bias',
              tensor([-0.4315,  0.2424,  0.3410, -0.3228, -0.2978,  0.1164,  0.0272, -0.3788],
                     device='cuda:0')),
             ('fc2.weight',
              tensor([[-0.3372, -0.2840, -0.3524, -0.1453,  0.2820, -0.1466,  0.2536, -0.3121]],
                     device='cuda:0')),
             ('fc2.bias', tensor([0.2877], device='cuda:0'))])

In [16]:
# Forma 1
# Salva apenas o estado dos pesos do modelo

# persistência
torch.save(model.state_dict(), '/tmp/model-weights.pth')

# carregamento
model = Net()
model.load_state_dict(torch.load('/tmp/model-weights.pth', weights_only=True))

<All keys matched successfully>

In [20]:
# Forma 2 (usa internamente o módulo pickle para serialização)
# Salva-se todo o objeto do modelo

# persistência
torch.save(model, '/tmp/model.pth')

# carregamento
model = torch.load('/tmp/model.pth')

/tmp/ipykernel_26951/3952427807.py:8: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model = torch.load('/tmp/model.pth')


# Referências 

* Documentação do Pytorch. Disponível em https://pytorch.org 
* Tutorial oficial do Pytorch. Disponível em https://pytorch.org/tutorials/beginner/basics/intro.html 
* Introdução ao Pytorch. Canal “Programação Dinâmica”. Disponível em https://www.youtube.com/watch?v=cGxv8tOaA7I 
* PyTorch Crash Course - Getting Started with Deep Learning. Canal AssemblyAI". Disponível em https://youtu.be/OIenNRt2bjg 
